### PR TITLE
Support thread-aware Profile.tree! on 1.8

### PR DESCRIPTION
**Pull request by jpsamaroo**
Adapts to changes in https://github.com/JuliaLang/julia/pull/41742, and requires https://github.com/JuliaLang/julia/pull/42162

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Aside: This supports indirect usage of FlameGraphs by Dagger through ProfileSVG, which doesn't appear to need any changes to account for the MT profiling changes.

**Comment by timholy** [comment]
I guess this will fail nightly until the 2nd PR is merged. If I don't notice, feel free to ping me, @jpsamaroo. Thanks for doing this!

**Comment by jpsamaroo** [comment]
I think we can wait for the Julia PR to be merged first so we don't mess up CI. It gives me a bit more time to test this with Dagger and make sure I didn't miss anything.

**Comment by timholy** [comment]
This doesn't pass but it's a step in the right direction. Let's merge it and move to the next issue.

**Pull request merged**
