### PR TITLE
Filter out the REPL-related stackframes by default

### LINKED ISSUE #4: Perhaps filter out the REPL related task
The Julia REPL filters out stackframes that are from the REPL task when e.g. displaying errors:

```
julia> error("foo")
ERROR: foo
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at REPL[13]:1

julia> stacktrace()
5-element Array{Base.StackTraces.StackFrame,1}:
 top-level scope at REPL[14]:1
 eval(::Module, ::Any) at boot.jl:330
 eval_user_input(::Any, ::REPL.REPLBackend) at REPL.jl:86
 macro expansion at REPL.jl:118 [inlined]
 (::REPL.var"#26#27"{REPL.REPLBackend})() at task.jl:333
```

Perhaps it would make sense for ProfileView.jl to do something similar by default (with an option to override?). In the ProfileView screenshot in the  README, an arguably large area is dedicated to these stackframes which are never really of any user interest.

### PR DESCRIPTION
**Pull request by timholy**
Closes #4

### CODE REVIEW

**Comment by timholy** [comment]
This still leaves one `eval`, but I don't think that's bad.

**Comment by KristofferC** [comment]
Would it make any sense to use the function in Base directly?:

https://github.com/JuliaLang/julia/blob/cb0cd9193a4a0a62f229ccffbd44eff56dbb6aba/base/client.jl#L85-L93

**Comment by timholy** [comment]
`data` is a zero-delimited collection of backtraces, so it would be possible. It's "rewrite lots of backtraces" rather than do surgery on a single tree, but there is a certain DRY attactiveness to doing it that way.

**Comment by timholy** [comment]
Oh, but you don't want to do lookup of all the ips redundantly; in profiling you might get the same exact backtrace 10^3 times, and it's crazy-slow to call `stacktrace` on each of them separately.

If we wanted to do it by inspecting raw ips, the right place would probably be https://github.com/JuliaLang/julia/blob/c2abaeedf8316a392035ff63fa6460595a9a5dd3/stdlib/Profile/src/Profile.jl#L608. But frankly I think it's easier this way.

**Comment by KristofferC** [comment]
:+1:

**Pull request merged**
