### PR TITLE
Fix deps for building docs

### PR DESCRIPTION
**Pull request by timholy**
Fixes https://github.com/timholy/FlameGraphs.jl/pull/12#issuecomment-583858979

### CODE REVIEW

**Comment by timholy** [comment]
Very odd; on Travis I'm getting
```julia
 Warning: invalid local image: unresolved path in index.md

│   link = "assets/ttfp.png"

└ @ Documenter.Writers.HTMLWriter ~/.julia/packages/Documenter/HmOsT/src/Writers/HTMLWriter.jl:1698

┌ Warning: invalid local image: unresolved path in index.md

│   link = "assets/customized_ttfp.png"

└ @ Documenter.Writers.HTMLWriter ~/.julia/packages/Documenter/HmOsT/src/Writers/HTMLWriter.jl:1698
```
but locally it works just fine.

**Comment by fredrikekre** [comment]
Maybe something related to "pretty urls", e.g. https://github.com/JuliaDocs/Documenter.jl/issues/921?

**Comment by timholy** [comment]
I tried commenting that out locally, but it didn't change anything. I also made sure to run it as stated in the `.travis.yml` file.

**Comment by mortenpi** [comment]
This is weird. As far as I can tell, it should work. @timholy Could you put a ``run(`tree`)`` into `make.jl` after `makedocs` so that we could see what the filesystem looks like after it runs?

**Comment by timholy** [comment]
It's as if they went "poof" into thin air. I don't know whether it's due to the doctest failures, which frankly are also weird given the filters I have defined. Any thoughts on next steps? The `@show` doesn't do anything useful, presumably because Documenter is running in some container or something? Should I cache the results to some file and show the file?

**Comment by kimikage** [comment]
I'm sorry for blocking the release, but I had thought this was simple a "[deps]" problem.

In at-blocks the output streams are redirected. However, using text files seems like a good idea to me, because this could be a problem with `save` (e.g." ImageMagic ").

**Comment by mortenpi** [comment]
Yeah, adding ImageMagick should fix this. I was able to reproduce it locally too and I end up with the following output:

```
julia> img = flamepixels(g);

Errors encountered while saving "/home/mortenpi/Julia/test/FlameGraphs.jl/docs/build/assets/ttfp.png".
All errors:
===========================================
ArgumentError: Package ImageMagick not found in current path:
- Run `import Pkg; Pkg.add("ImageMagick")` to install the ImageMagick package.

===========================================
ArgumentError: Argument does not support conversion to png.
===========================================

Fatal error:
```

**Comment by timholy** [comment]
The new docs seem to have built correctly. However there's one oddity on the Travis "requests" page: https://travis-ci.com/timholy/FlameGraphs.jl/requests

I've not seen those "not found" errors on the `gh-pages` branch before.

**Comment by kimikage** [comment]
Do you mean that it is a problem with the notification?
In fact, since ".travis.yml" does not exist, it is natural that it cannot be found. Even if ".travis.yml" exists, the requests marked as an error (red), when they are filtered by the branch name.

**Pull request merged**
